version: "3"
services:
  app:
    build:
      context: .
      dockerfile: ./docker-config/php/Dockerfile
    container_name: app
    volumes:
      - ./laravel:/var/www/laravel
    working_dir: /var/www/laravel
    depends_on:
      - mysql
      
  web:
    build:
      context: .
      dockerfile: ./docker-config/nginx/Dockerfile
    container_name: nginx
    ports:
      - 8080:80
    volumes:
      - .:/var/www
      - ./docker-config/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app

  mysql:
    build:
      context: .
      dockerfile: ./docker-config/mysql/Dockerfile
    container_name: mysql
    volumes:
      - ./docker-config/mysql/data:/var/lib/mysql
      - ./docker-config/mysql/my.cnf:/etc/mysql/conf.d/my.cnf
    depends_on:
      - mysql-volume

  mysql-volume:
    image: busybox
    tty: true
    volumes:
      - ./docker-config/mysql/data:/var/lib/mysql
