version: "3"
services:
  app:
    container_name: app
    build: ./php
    volumes:
      - ./php/src:/work
    depends_on:
      - mysql
      
  nginx:
    container_name: nginx
    image: nginx:1.20-alpine
    ports:
      - 8080:80
    volumes:
      - ./php/src:/work
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
    working_dir: /work

  mysql:
    container_name: mysql
    build: ./mysql
    volumes:
      - db-store:/var/lib/mysql

volumes:
  db-store: